<?php

use App\Http\Controllers\AtelierController;
use App\Http\Controllers\ClientController;
use Illuminate\Support\Facades\Route;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               


Route::get('/', function () {
    return view('welcome');
});

Route::get('/clients/enregistrement' , [ClientController::class , 'enregistrement']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
Route::get('/clients/enregistrer' , [ClientController::class , 'enregistrer']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
Route::get('/clients/connexion' , [ClientController::class , 'connexion']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Route::get('/clients/connecter' , [ClientController::class , 'connecter']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Route::get('/clients/espace' , [ClientController::class , 'espace']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Route::get('/clients/profil' , [ClientController::class , 'profil']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
Route::get('/clients/deconnecter' , [ClientController::class , 'deconnecter']);                                                                   

Route::get('/ateliers/programmes', [AtelierController::class, 'programmes']);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Route::get('/ateliers/passes',[AtelierController::class, 'passes']);
